### ISSUE TITLE
Christopher Battiston

### ISSUE THREAD

**Issue by aldefouw** [aldefouw/redcap_cypress#36]
**Operating System:** ?

**Test Environment:** ?

**Comment by darthpathos76** [comment]
Operating System - Windows Server 2012 R2 
Test Environment - REDCap 8.10.0 and 9.4.2 (two different test environments for two different platforms)

**Comment by aldefouw** [comment]
@darthpathos76 - I think what I was looking for was what OS and Test Environment you're hoping to configure your Cypress tests for ...

I'm assuming the OS you listed is your production server environment?

Here's a graphic that might help:
<img width="1259" alt="Screen Shot 2020-02-13 at 8 32 01 AM" src="https://user-images.githubusercontent.com/5683133/74445006-4ff95a00-4e3b-11ea-8ddf-818c4c741c21.png">

I'm basically looking for your Host Operating System (which I think was MacOS?) and then what your Test Environment is (and I think you were working on a Docker setup last time we checked?).

You might want to make a Docker container with Windows base OS image:
https://hub.docker.com/_/microsoft-windows-base-os-images



This is what my answers to these questions are:

Operating System: MacOSX Catalina 10.15

Test Environment: Docker Container running CentOS 7 / PHP 7
