### ISSUE TITLE
Export Data

### ISSUE THREAD

**Issue by aldefouw** [aldefouw/redcap_cypress#9]
**File Location:**
https://github.com/aldefouw/redcap_cypress/blob/master/cypress/integration/core/post-production/export_data.js

**Task:** 
Write the test specs as outlined in manual test script

**Please see CORE Validation Test Scripts project for more info:**
https://github.com/aldefouw/redcap_cypress/projects

Contact **Adam De Fouw** (aldefouw@medicine.wisc.edu) with any questions.

**Comment by AndrewPoppe** [comment]
#53 Pull Request addressing this issue
